config/routes.rb
Rails.application.routes.draw do
  
  # get '/' , to: 'home#home'
  # get '/home' , to: 'home#home'
  # # get '/home' , to: 'home#home', as: :home_path

  

  namespace :authentication, path: '' , as: '' do
    resources :users, only: [:new,:create]
    resources :sessions, only: [:new,:create]
    get '/sessions/destroy' , to: 'sessions#destroy'
  end

  namespace :finanzas, path: '' , as: '' do
    resources :categorias, only: [:index,:new,:create,:update,:edit]
    resources :ingresos, only: [:index,:new,:create,:update,:edit,:show]
    resources :egresos, only: [:index,:new,:create,:update,:edit,:show]

    get '/categorias' , to: 'categorias#index'
    get '/ingresos/destroy/:id' , to: 'ingresos#destroy' 
    get '/egresos/destroy/:id' , to: 'egresos#destroy' 
    # get '/categorias/:id' , to: 'categorias#update' as: :update_categorias
  end
  namespace :inicio, path: '' , as: '' do
    resources :home, path: '/'
  end
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categorium.rb
class Categorium < ApplicationRecord

    validates :categoria, presence: true
    validates :tipo, presence: true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/ingreso.rb
class Ingreso < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence:true, uniqueness: true
    validates :username, presence:true, uniqueness: true, length: {in: 3..15}
    validates :password, length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user 
    before_action :protect_pages
    def set_current_user
         Current.user = User.find_by(id:session[:user_id]) if session[:user_id]
    end
    def protect_pages
        redirect_to new_session_path unless Current.user    
    end
end

app/controllers/authentication/sessions_controller.rb
class Authentication::SessionsController < ApplicationController
    skip_before_action :protect_pages
    def new
        @user = User.new
    end
    def create
        @user = User.find_by("email = :login OR username = :login", {login: params[:correo]})        
        # pp @user 
        if @user&.authenticate(params[:password])
            session[:user_id] = @user.id
            # redirect_to home_path, notice: t('Creado')
            redirect_to '/home' 
        else
            render :new, status: :unprocessable_entity
        end
    end
    def destroy
        reset_session
        redirect_to '/' 
    end
end

app/controllers/authentication/users_controller.rb
class Authentication::UsersController < ApplicationController
    skip_before_action :protect_pages
    def new
        @user = User.new
    end
    def create
        pp user_params
        @user = User.new (user_params)

        if @user.save
            session[:user_id] = @user.id
            redirect_to '/home'
        else
            render :new ,status: :unprocessable_entity
        end
    end
    def user_params
        params.require(:user).permit(:email,:username,:password,:telefono,:nombre)
    end
end

app/controllers/finanzas/categorias_controller.rb
class Finanzas::CategoriasController < ApplicationController
    def index
        @categoria = Categorium.all
        pp @categoria
    end
    def new
        @categoria = Categorium.new
        pp @categoria
    end
    def create
        @categoria = Categorium.new (categoria_params)
        if @categoria.save
            redirect_to '/categorias'
        else
            render :new ,status: :unprocessable_entity
        end
    end
    def edit
        @categoria = Categorium.find([params[:id]])
        pp params
    end
    def update
        pp "Datos update:"
        @categoria = Categorium.find_by(id:[params[:id]])
        if @categoria.update(categoria_params)
            redirect_to '/categorias'
        else
            render :edit, status: :unprocessable_entity
        end
        
    end
    private
    def categoria_params
        params.require(:categorium).permit(:categoria, :tipo ,:icono)
    end
end

app/controllers/finanzas/egresos_controller.rb
class Finanzas::EgresosController < ApplicationController
    def index
        @ingreso = Ingreso.where(tipo:2)
        @fecha1 = Date.today
        @fecha2 = Date.today
        if params[:inicio].present? && params[:fin].present?
            @ingreso = Ingreso.where(tipo:2,fecha: (params[:inicio] .. params[:fin]))
            @fecha1 = params[:inicio]
            @fecha2 = params[:fin]
        end
    end
    def new
        @ingreso = Ingreso.new
        @categoria = Categorium.where(tipo:2)
       
    end
    def create
        @ingreso = Ingreso.new (get_params)
        if @ingreso.save
            redirect_to '/egresos'
        else
            render :new ,status: :unprocessable_entity
        end
    end
    def edit
        @ingreso = Ingreso.find(params[:id])
        @categoria = Categorium.where(tipo:2)
    end
    def update
        @ingreso = Ingreso.find_by(id:[params[:id]])
        if @ingreso.update(get_params)
            redirect_to '/egresos'
        else
            render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @ingreso = Ingreso.find_by(id:[params[:id]])
        @ingreso.destroy

        redirect_to '/egresos' 
    end
    private
    def get_params
        params.require(:ingreso).permit(:id_categoria,:fecha,:monto,:comentario,:tipo)
    end
end

app/controllers/finanzas/ingresos_controller.rb
class Finanzas::IngresosController < ApplicationController
    def index
        @ingreso = Ingreso.where(tipo:1)
        @fecha1 = Date.today
        @fecha2 = Date.today
        if params[:inicio].present? && params[:fin].present?
            @ingreso = Ingreso.where(tipo:1,fecha: (params[:inicio] .. params[:fin]))
            @fecha1 = params[:inicio]
            @fecha2 = params[:fin]
        end
    end
    def new
        @ingreso = Ingreso.new
        @categoria = Categorium.where(tipo:1)
        pp @categoria
    end
    def create
        @ingreso = Ingreso.new (get_params)
        if @ingreso.save
            redirect_to '/ingresos'
        else
            render :new ,status: :unprocessable_entity
        end
    end
    def edit
        @ingreso = Ingreso.find(params[:id])
        @categoria = Categorium.where(tipo:1)
    end
    def update
        @ingreso = Ingreso.find_by(id:[params[:id]])
        if @ingreso.update(get_params)
            redirect_to '/ingresos'
        else
            render :edit, status: :unprocessable_entity
        end
    end
    def destroy
        @ingreso = Ingreso.find_by(id:[params[:id]])
        @ingreso.destroy

        redirect_to '/ingresos' 
    end
    private
    def get_params
        params.require(:ingreso).permit(:id_categoria,:fecha,:monto,:comentario,:tipo)
    end
end

app/controllers/inicio/home_controller.rb
class Inicio::HomeController < ApplicationController

    def show
        @categoriaIng = Categorium.where(tipo:1)
        @categoriaEgr = Categorium.where(tipo:2)
        @model = Ingreso.where(fecha:Date)
        @fecha1 = Date.today
        @fecha2 = Date.today
        if params[:inicio].present?
            @fecha1 = params[:inicio]
            @fecha2 = params[:fin]
        end
        pp "Fechas"
        pp @fecha1, @fecha2
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/finanzas/categorias/edit.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Editar categorias</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row">
                    <div class="col-12" style="margin-top:2%">
                    <%= form_with(model: @categoria, url: categoria_path) do |form| %>
                            <div class="mb-3">
                                <%= form.label :categoria , :class => 'form-label' %>
                                <%= form.text_field :categoria , :class => 'form-control' %>
                            </div>
                            <div class="mb-3">
                                <%= form.label :tipo , :class => 'form-label' %>
                                <%= form.select :tipo, [["Ingreso", "1"], ["Egreso", "2"]] , :class => 'form-control' %>
                            </div>
                            <div class="mb-3">
                            <%= form.label :icono , :class => 'form-label' %>
                            <%= form.select :icono, [["Comida", "utensils"], ["Medico", "hospital-user"],["Sueldo","coins"]] , :class => 'form-control' %>
                        </div>
                            <div class="mb-3">
                            <%= form.submit "Editar categoria", :class => "btn btn-success" %>
                           </div>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

    <script>
        $(document).ready( function () {
            $('#tableCategoria').DataTable();
        } );
    </script>

app/views/finanzas/categorias/index.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Categorias</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 ">
                        <a href="/categorias/new" class="btn btn-success"><i class="far fa-plus-square"></i>&nbsp;Crear</a>
                    </div>
                    <div class="col-12" style="margin-top:2%">
                        <table class="table table-sm" id="tableCategoria">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Categoria</th>
                                    <th>Tipo</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @categoria.each do |item|  %>
                                    <tr>
                                        <td><%= item.id %></td>
                                        <td><i class="fas fa-<%=item.icono %>" ></i> <%= item.categoria %></td>
                                        <td>
                                            <% if item.tipo == 1%> 
                                            Ingreso
                                            <% else %> 
                                            Egreso
                                            <% end %>
                                        </td>
                                        <td>
                                        <%= link_to edit_categoria_path(item.id) do %><i class="fas fa-edit"></i>  Editar <% end %> &nbsp;                                            
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

    <script>
        $(document).ready( function () {
            $('#tableCategoria').DataTable();
        } );
    </script>

app/views/finanzas/categorias/new.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Crear categorias</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row">
                    <div class="col-12" style="margin-top:2%">
                    <%= form_with(model:@categoria ,url: categorias_path) do |form| %>
                        <% @categoria.errors.full_messages.each do |error| %>
                            <div><%= error %> <% end %> </div>
                        <div class="mb-3">
                            <%= form.label :categoria , :class => 'form-label' %>
                            <%= form.text_field :categoria , :class => 'form-control' %>
                        </div>
                        <div class="mb-3">
                            <%= form.label :tipo , :class => 'form-label' %>
                            <%= form.select :tipo, [["Ingreso", "1"], ["Egreso", "2"]] , :class => 'form-control' %>
                        </div>
                        <div class="mb-3">
                            <%= form.label :icono , :class => 'form-label' %>
                            <%= form.select :icono, [["Comida", "utensils"], ["Medico", "hospital-user"],["Sueldo","coins"]] , :class => 'form-control' %>
                        </div>
                        <div class="mb-3">
                        <%= form.submit "Crear categoria", :class => "btn btn-success" %>
                       </div>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

    <script>
        $(document).ready( function () {
            $('#tableCategoria').DataTable();
        } );
    </script>

app/views/finanzas/egresos/edit.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Editar egreso</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row">
                    <div class="col-10" style="margin-top:2%">
                    <%= form_with(model:@ingreso ,url: egreso_path) do |form| %>
                        <% @ingreso.errors.full_messages.each do |error| %>
                            <div><%= error %> <% end %> </div>
                        <div class="mb-3">
                            <%= form.label :fecha , :class => 'form-label' %>
                            <%= form.date_field :fecha , :class => 'form-control' %>
                        </div>
                        <%= form.collection_select :id_categoria, @categoria, :id, :categoria , :class => 'form-select' %>
                        <div class="mb-3">
                            <%= form.label :monto , :class => 'form-label' %>
                            <%= form.number_field :monto , :class => 'form-control' %>
                        </div>
                        <div class="mb-3">
                            <%= form.label :comentario , :class => 'form-label' %>
                            <%= form.text_field :comentario , :class => 'form-control' %>
                        </div>
                        <div class="mb-3" hidden>
                        <%= form.label :tipo , :class => 'form-label' %>
                        <%= form.text_field :tipo , :class => 'form-control', :value=> '2' %>
                    </div>
                        <div class="mb-3">
                        <%= form.submit "Editar egreso", :class => "btn btn-success" %>
                       </div>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

    <script>
        $(document).ready( function () {
            $('#tableCategoria').DataTable();
        } );
    </script>

app/views/finanzas/egresos/index.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Egreso</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row"> 
                    <div class="col-2 ">
                        <a href="/egresos/new" class="btn btn-success"><i class="far fa-plus-square"></i>&nbsp; Crear</a>
                    </div>
                    <div class="col-4">
                    <%= form_with url: egresos_path , method: :get do |form| %>
                        <div class="mb-3">
                          <%= form.label :inicio , :class=> 'form-label' %>
                            <%= form.date_field :inicio , :class=> 'form-control', :value => @fecha1,
                            onChange: 'this.form.requestSubmit()' %>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3">
                          <%= form.label :fin , :class=> 'form-label' %>
                            <%= form.date_field :fin , :class=> 'form-control', :value => @fecha2,
                            onChange: 'this.form.requestSubmit()' %>
                        </div>
                        <% end %> 
                      </div>
                    </div>
                    <div class="col-12" style="margin-top:2%">
                        <table class="table table-sm" id="tableCategoria">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Categoria</th>
                                    <th>Fecha</th>
                                    <th>Monto</th>
                                    <th>Comentario</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @ingreso.each do |item|  %>
                                    <% @cat = Categorium.find(item.id_categoria) %>
                                    <tr>
                                        <td><%= item.id %></td>
                                        <td>
                                            <i class="fas fa-<%= @cat.icono %>" ></i>      
                                            <%= @cat.categoria %>
                                        </td>
                                        <td><%= item.fecha %></td>
                                        <td>$ <%= item.monto %></td>
                                        <td><%= item.comentario %></td>
                                        <td>
                                        <%= link_to edit_egreso_path(item.id) do %><i class="fas fa-edit"></i>  Editar <% end %> &nbsp;        
                                            <a style="color:red" href="/egresos/destroy/<%= item.id %>"><i class="fas fa-trash"></i> Eliminar</a>                                    
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

app/views/finanzas/egresos/new.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Registrar egreso</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row">
                <div class="col-10"><a class="btn btn-primary" href="/categorias/new">Nueva categoria </a></div>
                    <div class="col-10" style="margin-top:2%">
                    <%= form_with(model:@ingreso ,url: egresos_path) do |form| %>
                        <% @ingreso.errors.full_messages.each do |error| %>
                            <div><%= error %> <% end %> </div>
                        <div class="mb-3">
                            <%= form.label :fecha , :class => 'form-label' %>
                            <%= form.date_field :fecha , :class => 'form-control' %>
                        </div>
                        <%= form.collection_select :id_categoria, @categoria, :id, :categoria , :class => 'form-select' %>
                        <div class="mb-3">
                            <%= form.label :monto , :class => 'form-label' %>
                            <%= form.number_field :monto , :class => 'form-control' %>
                        </div>
                        <div class="mb-3">
                            <%= form.label :comentario , :class => 'form-label' %>
                            <%= form.text_field :comentario , :class => 'form-control' %>
                        </div>
                        <div class="mb-3" hidden>
                        <%= form.label :tipo , :class => 'form-label' %>
                        <%= form.text_field :tipo , :class => 'form-control', :value=> '2' %>
                    </div>
                        <div class="mb-3">
                        <%= form.submit "Agregar egreso", :class => "btn btn-success" %>
                       </div>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

    <script>
        $(document).ready( function () {
            $('#tableCategoria').DataTable();
        } );
    </script>

app/views/finanzas/ingresos/edit.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Editar ingreso</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row">
                    <div class="col-10" style="margin-top:2%">
                    <%= form_with(model:@ingreso ,url: ingreso_path) do |form| %>
                        <% @ingreso.errors.full_messages.each do |error| %>
                            <div><%= error %> <% end %> </div>
                        <div class="mb-3">
                            <%= form.label :fecha , :class => 'form-label' %>
                            <%= form.date_field :fecha , :class => 'form-control' %>
                        </div>
                        <%= form.collection_select :id_categoria, @categoria, :id, :categoria , :class => 'form-select' %>
                        <div class="mb-3">
                            <%= form.label :monto , :class => 'form-label' %>
                            <%= form.number_field :monto , :class => 'form-control' %>
                        </div>
                        <div class="mb-3">
                            <%= form.label :comentario , :class => 'form-label' %>
                            <%= form.text_field :comentario , :class => 'form-control' %>
                        </div>
                        <div class="mb-3" hidden>
                        <%= form.label :tipo , :class => 'form-label' %>
                        <%= form.text_field :tipo , :class => 'form-control', :value=> '1' %>
                    </div>
                        <div class="mb-3">
                        <%= form.submit "Editar ingreso", :class => "btn btn-success" %>
                       </div>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

    <script>
        $(document).ready( function () {
            $('#tableCategoria').DataTable();
        } );
    </script>

app/views/finanzas/ingresos/index.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Ingresos</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row">
                    <div class="col-2 ">
                        <a href="/ingresos/new" class="btn btn-success"><i class="far fa-plus-square"></i>&nbsp;Crear</a>
                    </div>
                    <div class="col-4">
                    <%= form_with url: ingresos_path , method: :get do |form| %>
                        <div class="mb-3">
                          <%= form.label :inicio , :class=> 'form-label' %>
                            <%= form.date_field :inicio , :class=> 'form-control', :value => @fecha1,
                            onChange: 'this.form.requestSubmit()' %>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="mb-3">
                          <%= form.label :fin , :class=> 'form-label' %>
                            <%= form.date_field :fin , :class=> 'form-control', :value => @fecha2,
                            onChange: 'this.form.requestSubmit()' %>
                        </div>
                        <% end %> 
                      </div>
                    </div>
                    <div class="col-12" style="margin-top:2%">
                        <table class="table table-sm" id="tableCategoria">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Categoria</th>
                                    <th>Fecha</th>
                                    <th>Monto</th>
                                    <th>Comentario</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @ingreso.each do |item|  %>
                                    <% @cat = Categorium.find(item.id_categoria) %>
                                    <tr>
                                        <td><%= item.id %></td>
                                        <td>
                                            <i class="fas fa-<%= @cat.icono %>" ></i>      
                                            <%= @cat.categoria %>
                                        </td>
                                        <td><%= item.fecha %></td>
                                        <td>$ <%= item.monto %></td>
                                        <td><%= item.comentario %></td>
                                        <td>
                                        <%= link_to edit_ingreso_path(item.id) do %><i class="fas fa-edit"></i>  Editar <% end %> &nbsp;    
                                            <a style="color:red" href="/ingresos/destroy/<%= item.id %>"><i class="fas fa-trash"></i> Eliminar</a>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

    <script>
        $(document).ready( function () {
            $('#tableCategoria').DataTable();
        } );
    </script>

app/views/finanzas/ingresos/new.html.erb
<%= render 'shared/menu' %>
    <div class="container" style="margin-left:18%">
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <h4>Registrar ingreso</h4>
            </div>
        </div>
        <div class="card" aria-hidden="true">
            <div class="card-body">
                <div class="row">
                    <div class="col-10"><a class="btn btn-primary" href="/categorias/new">Nueva categoria </a></div>
                    <div class="col-10" style="margin-top:2%">
                    <%= form_with(model:@ingreso ,url: ingresos_path) do |form| %>
                        <% @ingreso.errors.full_messages.each do |error| %>
                            <div><%= error %> <% end %> </div>
                        <div class="mb-3">
                            <%= form.label :fecha , :class => 'form-label' %>
                            <%= form.date_field :fecha , :class => 'form-control' %>
                        </div>
                        <%= form.collection_select :id_categoria, @categoria, :id, :categoria , :class => 'form-select' %>
                        <div class="mb-3">
                            <%= form.label :monto , :class => 'form-label' %>
                            <%= form.number_field :monto , :class => 'form-control' %>
                        </div>
                        <div class="mb-3">
                            <%= form.label :comentario , :class => 'form-label' %>
                            <%= form.text_field :comentario , :class => 'form-control' %>
                        </div>
                        <div class="mb-3" hidden>
                        <%= form.label :tipo , :class => 'form-label' %>
                        <%= form.text_field :tipo , :class => 'form-control', :value=> '1' %>
                    </div>
                        <div class="mb-3">
                        <%= form.submit "Agregar ingreso", :class => "btn btn-success" %>
                       </div>
                    <% end %>
                    </div>
                </div>
            </div>
        </div>
        <%= stylesheet_link_tag  %>
    </div>

    <script>
        $(document).ready( function () {
            $('#tableCategoria').DataTable();
        } );
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Finanzas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
  
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
</html>